[provider]
cluster = "mainnet"
wallet = "~/.config/solana/treasury.json"

[programs.mainnet]
moonticket_jackpot = "GmyMFG4QwHh2YK4bjy489eBzf9Hzf3BLZ1sFfznoeWpB"

[scripts]
test = "mocha -t 1000000 tests/moonticket-jackpot.test.js"
